export const text = {
  productName: "AI Gallery",
  productTagline: "本地创作档案",
  mainNavigationLabel: "主导航",
  rootElementMissing: "无法找到应用根节点",
  nav: {
    library: "作品库",
    projects: "项目",
    efficiency: "创作效率",
    review: "待审核",
    settings: "设置",
  },
  shell: {
    eyebrow: "LOCAL ARCHIVE · 001",
    title: "让每一次生成，\n都留下清晰脉络。",
    description:
      "图片、短片与提示词只留在你的设备。轻量应用壳已经就绪，作品数据将在工作区建立后按页加载。",
    createWorkspace: "创建工作区",
    openWorkspace: "打开已有工作区",
    workspaceActionsUnavailable: "工作区功能将在下一个工程里程碑开放。",
    emptyTitle: "等待第一件作品",
    emptyDescription:
      "当前没有打开的工作区。应用启动不会扫描媒体或预载原始文件。",
    privacy: "默认离线",
    loading: "正在打开页面…",
  },
  theme: {
    light: "切换到浅色主题",
    dark: "切换到深色主题",
  },
  settings: {
    eyebrow: "PREFERENCES",
    title: "设置",
    description:
      "管理工作区备份、只读展示模式和按需 AI 分类服务。所有操作都只在你明确触发时执行。",
    back: "返回作品库",
  },
  workspace: {
    eyebrow: "WORKSPACE SAFETY",
    title: "备份与访问模式",
    description: "备份仅在你主动发起时执行；恢复不会覆盖已有工作区。",
    unavailable: "请先在作品库连接工作区后再管理备份和访问模式。",
    backupKind: "备份类型",
    fullBackup: "完整备份",
    lightBackup: "轻量备份",
    fullBackupHint:
      "包含受管媒体、数据库和工作区内容；外部引用文件不会被复制。",
    lightBackupHint:
      "只包含数据库和工作区描述，不含媒体；恢复后受管媒体可能缺失。",
    backupDestination: "备份保存目录",
    backupDestinationPlaceholder: "例如 D:\\AI-Gallery-Backups",
    backupDestinationRequired: "请先选择备份保存目录。",
    selectBackupDestination: "选择备份目录",
    createBackup: "创建备份",
    creatingBackup: "正在创建备份…",
    backupCreated: (name: string, managed: number, external: number) =>
      `已创建备份「${name}」：${managed} 个受管媒体；${external} 个外部引用需自行迁移。`,
    restoreTitle: "恢复备份",
    backupRoot: "备份目录",
    backupRootPlaceholder: "例如 D:\\AI-Gallery-Backups\\backup-001",
    backupSourceRequired: "请先选择要恢复的备份目录。",
    selectBackupSource: "选择备份来源",
    restoreTarget: "恢复目标工作区",
    restoreTargetPlaceholder: "例如 D:\\Restored-AI-Gallery",
    restoreTargetRequired: "请先选择恢复目标工作区。",
    selectRestoreTarget: "选择恢复父目录",
    restoreTargetHint:
      "恢复只能写入尚不存在的新目录；选择父目录后会自动生成新的工作区名称，也可手动填写新路径。",
    restore: "恢复到目标工作区",
    restoring: "正在恢复…",
    restoreConfirm:
      "恢复会创建或修改目标工作区。请确认备份来源可信，且目标位置符合提示。",
    restored: "恢复完成。",
    accessModeTitle: "展示访问模式",
    readWriteDescription: "当前可管理作品、分类、导入和 AI 服务。",
    readOnlyActive: "只读展示中",
    readOnlyDescription: "只读展示模式下仅保留浏览、搜索、筛选、预览与复制。",
    enableReadOnly: "进入只读展示模式",
    disableReadOnly: "退出只读展示模式",
    disableReadOnlyConfirm:
      "确认退出只读展示模式？退出后将重新显示编辑、导入和管理操作。",
    modeUpdated: "访问模式已更新。",
    directoryPickerFailed: "无法打开目录选择器，请重试。",
    operationFailed: "工作区管理操作未完成，请稍后重试。",
  },
  ai: {
    settingsEyebrow: "AI PROVIDERS",
    settingsTitle: "AI 分类服务",
    settingsDescription:
      "服务只会在你明确发起分类时连接。密钥仅提交到系统安全存储，不会显示、回填或写入作品库。",
    providerList: "已配置的服务",
    providerEmpty: "尚未配置 AI 服务",
    providerFormTitle: "添加或编辑服务",
    providerKind: "服务类型",
    providerName: "显示名称",
    providerEndpoint: "服务地址",
    providerModel: "模型名称",
    providerTimeout: "超时时间（毫秒）",
    providerEnabled: "启用此服务",
    providerTextCapability: "允许文本分类",
    providerVisionCapability: "允许视觉分析（本阶段不发送媒体）",
    providerKey: "API 密钥（可选，仅本次提交）",
    providerKeyHint: "留空将保留已有系统凭据；不会回显已保存的密钥。",
    providerNeedsCredential: "需要重新配置密钥",
    providerReady: "凭据已配置",
    invalidProviderForm:
      "请填写服务名称、有效地址和模型名称；超时时间需为 1000–60000 毫秒。",
    addProvider: "添加服务",
    saveProvider: "保存服务",
    savingProvider: "正在保存…",
    providerSaved: "AI 服务配置已保存。",
    providerDeleted: "AI 服务配置已删除。",
    cancelEdit: "取消编辑",
    editProvider: "编辑",
    deleteProvider: "删除",
    testProvider: "测试连接",
    testingProvider: "正在测试…",
    testSucceeded: "连接测试通过。未发送作品、提示词或媒体。",
    confirmDeleteProvider:
      "确定删除此服务配置吗？系统安全存储中的对应密钥也会被删除。",
    loadFailed: "AI 服务配置暂时无法读取，请先连接工作区后重试。",
    operationFailed: "AI 操作未完成，请检查服务配置或稍后重试。",
    noWorkspace: "请先在作品库连接工作区。",
    sendPreviewTitle: "本次调用发送内容预览",
    sendPreviewDescription:
      "预览只显示字段类型，不显示字段内容。备注、路径、媒体、缩略图和生成参数不会发送。",
    previewTargetType: "目标类型",
    previewTargetId: "目标编号",
    previewTargetRequired: "请先填写有效的作品或项目编号。",
    preview: "查看预览",
    previewLoading: "正在生成预览…",
    previewEmpty: "输入目标编号后可查看本次调用的字段范围。",
    previewProvider: "用于生成建议的服务",
    createSuggestions: "生成待审核建议",
    creatingSuggestions: "正在生成建议…",
    suggestionInputRequired: "请选择服务，并填写有效的作品或项目编号。",
    suggestionsCreated: "建议已进入待审核列表，尚未写入正式分类。",
    asset: "作品",
    project: "项目",
    reviewEyebrow: "HUMAN REVIEW",
    reviewTitle: "待审核建议",
    reviewDescription:
      "AI 建议不会自动写入分类或标签。请逐条确认、修改，或明确拒绝。",
    reviewReadOnly:
      "只读展示模式下已隐藏 AI 审核操作。请在设置中明确退出只读模式后再管理建议。",
    reviewEmpty: "没有待审核建议",
    reviewLoadFailed: "待审核建议暂时无法读取，请稍后重试。",
    target: "目标",
    dimension: "分类维度",
    existingCategory: "建议分类",
    newCategory: "建议新分类",
    confidence: "置信度",
    reason: "理由",
    accept: "接受",
    reject: "拒绝",
    modify: "修改",
    resolveTitle: "处理 AI 建议",
    resolveDescription: "选择处理方式后才会写入正式分类或标签。",
    acceptExisting: "采用现有分类",
    createCategory: "创建或复用新分类",
    mergeIntoExisting: "合并到现有分类",
    convertToTag: "转为自由标签",
    categoryId: "分类编号",
    categoryName: "分类或标签名称",
    resolve: "确认处理",
    resolving: "正在处理…",
    close: "关闭",
    nextPage: "加载下一页",
    previousPage: "返回上一页",
    loading: "正在读取审核建议…",
  },
  library: {
    workspaceEyebrow: "LOCAL WORKSPACE",
    workspaceTitle: "连接你的本地作品库",
    workspaceDescription:
      "输入工作区根目录。路径只用于本地连接，不会出现在作品卡片或错误信息中。",
    workspacePath: "工作区路径",
    workspacePathPlaceholder: "例如 D:\\AI-Gallery",
    selectWorkspaceDirectory: "选择目录",
    createWorkspace: "创建新工作区",
    connectWorkspace: "连接工作区",
    connectingWorkspace: "正在连接…",
    workspacePathRequired: "请输入工作区路径。",
    loadingLibrary: "正在读取首屏作品…",
    loadFailed: "作品库暂时无法读取，请稍后重试。",
    retry: "重试",
    tabsLabel: "作品库视图",
    tabs: {
      assets: "作品",
      projects: "项目",
      taxonomy: "分类与标签",
      trash: "回收站",
    },
    addProject: "新建项目",
    addAsset: "新建作品记录",
    importMedia: "导入媒体",
    export: {
      chooseProjects: "选择项目",
      selectThisProject: "加入所选",
      cancelProjectSelection: "取消选择",
      selectPageProjects: "全选本页项目",
      selectedProjects: (count: number) => `已选择 ${count} 个项目`,
      selectedItems: (count: number) => `导出 ${count} 项`,
      exportSelected: "导出所选",
      title: "导出内容",
      description: "选择导出完整作品内容，或只导出提示词 JSON。",
      complete: "完整内容",
      completeDescription: "包含作品和项目数据、分类、备注及媒体文件副本。",
      prompts: "仅提示词 JSON",
      promptsDescription: "导出所选作品与项目的提示词，不包含媒体文件。",
      start: "选择位置并导出",
      exporting: "正在导出…",
      completed: (name: string) => `已导出：${name}`,
      failed: "导出失败，请检查所选内容数量、目标位置和媒体文件状态。",
      selectionLimit: "一次最多选择 100 个项目，请分批导出。",
    },
    workspaceReady: "工作区已连接",
    localOnly: "仅本地",
    assetCount: (count: number) => `${count} 件作品`,
    emptyAssets: "这一页还没有作品",
    emptyAssetsHint: "导入图片或 MP4，或先建立一条独立作品记录。",
    loadMore: "加载下一页",
    previousPage: "上一页",
    nextPage: "下一页",
    pagination: "作品分页",
    pageLabel: (page: number) => `第 ${page} 页`,
    pageSize: "每页显示",
    paginationSummary: (count: number) => `共 ${count} 件作品`,
    loadingMore: "正在加载…",
    image: "图片",
    video: "视频",
    unknownModel: "模型未记录",
    unknownPlatform: "平台未记录",
    noThumbnail: "缩略图待生成",
    thumbnailUnavailable: "缩略图暂不可用",
    noVideoCover: "未设置视频封面",
    search: "搜索作品",
    searchField: "搜索范围",
    searchTitle: "作品名",
    searchPrompt: "提示词",
    searchNotes: "备注",
    searchPlaceholder: (field: "title" | "prompt" | "notes") =>
      field === "title"
        ? "按作品名搜索（不区分大小写）"
        : field === "prompt"
          ? "按提示词搜索"
          : "按备注搜索",
    filters: "筛选",
    clearFilters: "清除筛选",
    filterBasics: "作品属性",
    filterTimeAndShape: "最后修改时间与画幅",
    filterType: "类型",
    filterModel: "模型",
    filterPlatform: "平台",
    filterRating: "评分",
    filterFavorite: "收藏",
    filterPublic: "公开",
    filterDate: "创建日期",
    any: "全部",
    yes: "是",
    no: "否",
    ratingAtLeast: (rating: number) => `${rating} 星及以上`,
    dateFrom: "修改日期起",
    dateTo: "修改日期止",
    minAspectRatio: "最小宽高比",
    maxAspectRatio: "最大宽高比",
    duplicateGroups: "重复项",
    duplicateGroupsTitle: "重复媒体组",
    duplicateGroupsDescription:
      "按内容哈希聚合，仅供查看与打开详情；不会执行删除或合并。",
    duplicateGroupsEmpty: "没有发现重复媒体",
    duplicateGroupCount: (count: number) => `${count} 个相同文件`,
    closePanel: "关闭面板",
    openDetail: "打开详情",
    untitled: "未命名作品",
    projectUntitled: "未命名项目",
    form: {
      createProject: "新建项目",
      editProject: "编辑项目",
      createAsset: "新建作品记录",
      editAsset: "编辑作品",
      title: "标题",
      description: "描述",
      projectKind: "项目形式",
      projectKindHint:
        "分类项目用于简单归类；画布项目可组织参考图片与最终输出。转换形式不会删除作品。",
      project: "所属项目",
      independent: "独立作品",
      model: "模型",
      platform: "平台",
      promptZh: "中文提示词",
      promptEn: "英文提示词",
      negativePrompt: "负面提示词",
      generationParams: "生成参数 JSON",
      invalidGenerationParams: "生成参数必须是 JSON 对象。",
      recognitionTitle: "待确认的图片元数据",
      recognitionDescription:
        "这是从图片中自动识别的内容。应用后仍可编辑，保存作品时才会写入正式字段。",
      recognitionAccept: "应用识别结果",
      recognitionReject: "忽略识别结果",
      notes: "备注",
      projectAssets: "归入作品编号（逗号分隔）",
      projectAssetsPlaceholder: "例如：1，2，15",
      projectAssetsHint:
        "保存时把这些展示编号对应的作品加入当前项目；原有项目中的作品会移动到这里。单次最多 100 件。",
      invalidProjectAssets: "作品编号格式无效，请使用逗号分隔的正整数。",
      projectSavedAssetsFailed:
        "项目基本信息已保存，但作品归入失败；请核对作品编号后重试。",
      confirmProjectAssets: (count: number) =>
        `确认把 ${count} 件作品归入当前项目？`,
      rating: "评分",
      favorite: "收藏",
      public: "公开",
      save: "保存",
      saving: "正在保存…",
      cancel: "取消",
      close: "关闭",
      required: "标题不能为空。",
      saved: "已保存更改。",
      confirmDiscard: "仍有未保存更改，确定放弃并关闭？",
    },
    project: {
      simpleKind: "分类项目",
      canvasKind: "画布项目",
      heading: "项目如何使用",
      description:
        "项目用于归纳同一主题、同一提示词或同一轮生成实验；作品也可以保持独立，不必放入项目。",
      idLabel: "项目编号",
      empty: "还没有项目",
      emptyHint: "用项目组织同一主题或同一轮生成实验。",
      edit: "编辑项目",
      open: "打开项目",
      back: "返回项目列表",
      includedWorks: "项目作品",
      includedWorksEmpty: "这个项目还没有归入作品。",
      selectPage: "全选本页项目作品",
      selectedCount: (count: number) => `已选择 ${count} 件作品`,
      removeSelected: "移出项目",
      removeSelectedLabel: "将所选作品移出当前项目",
      removeConfirm: (count: number) =>
        `确定将所选 ${count} 件作品移出项目吗？作品和媒体文件都会保留。`,
      removeFailed: "移出项目失败，未保存任何变更。",
      delete: "删除项目",
    },
    detail: {
      title: "作品详情",
      previewUnavailable: "预览暂不可用",
      metadata: "元数据",
      assetId: "作品编号",
      editOrder: "调整编号",
      targetOrder: "目标编号",
      orderSwap: "与已有编号交换",
      orderShift: "目标编号后的作品顺延一位",
      orderSave: "确认调整编号",
      notes: "备注",
      prompts: "提示词",
      taxonomy: "分类与标签",
      edit: "编辑",
      manageVideoCover: "设置视频封面",
      copyZh: "复制中文提示词",
      copyEn: "复制英文提示词",
      copyNegative: "复制负面提示词",
      copyParams: "复制全部参数",
      copyPath: "复制文件路径",
      copyJson: "复制 JSON 摘要",
      copyMarkdown: "复制 Markdown 摘要",
      copySuccess: "已复制到剪贴板。",
      dimensions: "尺寸",
      duration: "时长",
      model: "模型",
      platform: "平台",
      delete: "移入回收站",
      selectAllPage: "全选本页",
      selectAllResults: "全选筛选结果",
      selectAllLimit: "一次最多选择 100 件作品，请缩小筛选范围后分批处理。",
      selectedAssets: (count: number) => `已选择 ${count} 件作品`,
      moveSelectedToTrash: "移入回收站",
      moveSelectedToTrashAria: "将所选作品移入回收站",
    },
    import: {
      title: "导入媒体",
      description: "选择文件、文件夹或粘贴路径。默认复制进作品库。",
      sourcePaths: "媒体路径",
      sourcePlaceholder: "D:\\素材\\作品-01.png",
      selectFiles: "选择文件",
      selectDirectory: "选择文件夹",
      mode: "导入方式",
      copy: "复制进作品库（推荐）",
      reference: "引用原文件",
      targetProject: "导入到项目",
      start: "开始导入",
      empty: "请至少输入一个媒体路径。",
      progress: "导入进度",
      queued: "等待后台任务",
      running: "正在导入",
      completed: "导入完成",
      cancelled: "已取消导入",
      failed: "导入失败",
      cancel: "取消导入",
      another: "继续导入",
    },
    taxonomy: {
      title: "分类与标签",
      description: "分类按维度组织；自由标签可跨维度补充个人语义。",
      dimensionName: "维度名称",
      categoryName: "分类名称",
      targetDimension: "所属维度",
      tagName: "标签名称",
      addCategory: "添加分类",
      addDimension: "添加维度",
      addTag: "添加标签",
      empty: "尚未建立分类体系。",
      delete: "删除分类",
      openCategory: (name: string) => `打开分类：${name}`,
      backToTaxonomy: "返回分类与标签",
      editCategory: "编辑",
      editCategoryTitle: (name: string) => `编辑分类：${name}`,
      editCategoryDescription:
        "修改名称，或将此分类的作品关系合并到同一维度的其他分类。",
      categoryAssets: (count: number) => `${count} 件作品`,
      categoryEmpty: "这个分类下还没有作品。",
      saveCategoryName: "保存名称",
      mergeTarget: "合并到其他分类",
      chooseMergeTarget: "请选择目标分类",
      mergeCategory: "合并分类",
      confirmMerge: "确认合并",
      mergeConfirmTitle: (name: string) => `确认合并“${name}”？`,
      mergeConfirmDescription:
        "作品会改为目标分类，原分类随后删除；作品和媒体文件不会删除。",
      deleteConfirmDescription: "只移除这项分类关系；作品和媒体文件不会删除。",
      deleteDimension: "删除维度",
      rename: "重命名",
      renamePrompt: "请输入新名称",
      deleteDimensionConfirm: "确定删除这个维度？请先清空其中分类。",
      deleteDimensionFailed: "维度仍有分类或关联，无法删除。",
      deleteTagConfirm: "确定删除这个标签？已有关联将被移除。",
      affected: (count: number) => `将影响 ${count} 件作品`,
      replacement: "合并到其他分类（可选）",
      removeOnly: "仅移除分类关系",
      tags: "自由标签",
      switchLabel: "分类管理视图",
      taxonomyView: "分类与标签",
      metadataView: "元数据预设",
      models: "模型预设",
      platforms: "平台预设",
      addPreset: "添加预设",
      deletePreset: "删除",
      presetName: (kind: string) => `${kind}名称`,
      usedBy: (count: number) => `${count} 件作品使用`,
      renamePresetPrompt: "请输入新的预设名称",
      deletePresetConfirm: (name: string, count: number) =>
        `确定删除“${name}”？${count} 件作品中的该元数据会被清空。`,
      presetSaveFailed: "预设保存失败，请检查名称是否重复。",
      presetDeleteFailed: "预设删除失败，请稍后重试。",
    },
    trash: {
      title: "回收站",
      description: "移入回收站默认只删除记录，原始媒体仍会保留。",
      empty: "回收站是空的",
      restore: "恢复",
      restoreSelected: "恢复所选",
      selectAllPage: "全选本页",
      selectedItems: (count: number) => `已选择 ${count} 条记录`,
      permanentSelected: "永久删除所选记录",
      undo: "撤销最近删除",
      permanent: "永久删除记录",
      confirmTitle: "确认移入回收站？",
      confirmDescription: "作品记录将进入回收站，原始媒体不会被删除。",
      confirmMove: "确认移入",
      confirmProjectTitle: "确认将项目移入回收站？",
      confirmProjectDescription:
        "项目记录将进入回收站，项目内作品保留并暂时变为独立作品。",
      permanentTitle: "永久删除这条记录？",
      permanentDescription: "此操作无法撤销。应用仍不会主动删除原始媒体文件。",
      permanentAgain: "我已了解，永久删除",
      permanentSelectedTitle: (count: number) => `永久删除 ${count} 条记录？`,
      preserved: "原始媒体已保留",
    },
  },
  nsfw: {
    brand: "AI Gallery · PRIVATE",
    workspaceEyebrow: "PRIVATE WORKSPACE",
    workspaceTitle: "连接独立的 NSFW 作品库",
    workspaceDescription:
      "请选择与正常作品库互不嵌套的独立目录。这里的作品、项目、分类、预设和设置不会写入正常作品库。",
    workspaceReady: "私密工作区已连接",
    localOnly: "独立私密库",
    tabs: {
      assets: "NSFW作品",
      projects: "NSFW项目",
      taxonomy: "NSFW分类与标签",
      trash: "NSFW回收站",
    },
    addProject: "新建NSFW项目",
    importMedia: "导入NSFW媒体",
    exit: "退出NSFW",
    activating: "正在唤醒私密作品库…",
  },
} as const;
